# for server.js
GET http://localhost:5005/
###

# for index.js
GET http://localhost:5005/transactions?&search=4tb
###
GET http://localhost:5005/transactions?month=&search=550&page=1&size=5
###
# http://localhost:5005/transactions?&search=&page=1&size= -> this is invalid coz size is empty if u mention size then 
# u must give value coz when u give size then it will be used in the query to get the value then it returns undefined nd makes invalid request

GET http://localhost:5005/statistics?month=6
### month=6 ; no month value gives total year data

GET http://localhost:5005/price-range?month=6
###

GET http://localhost:5005/categories?month=6
###

GET http://localhost:5005/combined-data/?month=
###

